modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
    modId="bililive"
    version="1.0.2"
    displayName="BiliLive"
	authors="ppoozl"
    description='''
    Bilibili 直播弹幕库
    '''

[[dependencies.BiliLive]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"